### ISSUE TITLE
GFFUtils: gff_annotation_extractor: Warning: No parent data for feature 'BSU23850'

### ISSUE THREAD

**Issue by schhabra1** [fls-bioinformatics-core/GFFUtils#43] opened 2020-11-06 23:19 UTC
Hello,

I am new to RNA-seq analysis and would appreciate a help to resolve an issue I am having with running gff_annotation_extractor command. I am trying to annotate the data I got from term-seq, Salmon and DESeq2 analysis. My annotation file is a .gff file downloaded from NCBI for Bacillus subtilis bacteria (see a snapshot below) and input is .csv file with first column as either transcripts/ geneID or 3' end of coordinates. The command I am running in venv is:
```
gff_annotation_extractor -o test_annot2.txt --id-attribute=ID --type=old_locus_tag GCF_000009045.1_ASM904v1_genomic.gff diffexpr-results-pw.csv
```
It returns a warning
```
Warning: No parent data for feature 'BSU40140,ILL.yydJ-BSU40140.1~723'. 
```
The same warning for each transcript.

I have tried various different options including converting my csv files into tab delimited txt files but it gives the same error.  The output file has the columns from input copied again into next columns and only column headers: ID,Name	exon_parent	feature_type_exon_parent	gene_ID	gene_name	chr	start	end	strand	gene_length	locus	description but no data in these columns. I am not able to point out what I am doing wrong here. Any help is appreciated!

Thanks.
<img width="946" alt="annotation_file" src="https://user-images.githubusercontent.com/69992153/98423264-2123b380-205c-11eb-89cf-54d3e1b61181.png">

**Comment by pjbriggs** [comment] 2020-11-23 14:46
Hello @schhabra1 

Sorry you've encountered a problem with the `gff_annotation_extractor`, and apologies not to respond sooner.

I suspect that the problem is that you're supplying a CSV file, but the program expects a tab-delimited file. So it has read the whole of each line from `diffexpr-results-pw.csv` as the feature ID, instead of just the first field (e.g. `BSU40140` rather than `BSU40140,ILL.yydJ-BSU40140.1~723` in your example). The warnings occur because there are no records in the GFF where the `ID` attribute matches this value.

The requirement for a tab-delimited file is perhaps not made clearly enough in the documentation.

Please try changing the CSV file to tabs and rerunning the program, and let me know whether this helps.

**Comment by schhabra1** [comment] 2020-12-30 05:03
Hello @pjbriggs 

Thank you for your reply. Sorry I could not respond earlier.

You are right, I should use tab-delimited version; it is mentioned at one place in the documentation that it takes a tab-delimited input (although you have to carefully look for it).

I tried using the tab-delimited txt file, and I am getting a duplicate values error. I think I need to remove duplicates from my gff file and re-run the annotation. Hopefully, it will work! 

Thanks again!

**Comment by pjbriggs** [comment] 2021-01-05 08:55
Hello @schhabra1 - no problem! Thanks for the update. If you feel this issue is resolved then please feel free to close it and open a new issue if you encounter another problem subsequently.

**Closed** 2021-01-07 23:09 UTC
